name: Deploy to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v4

      # 2. Write the private key to a file
      - name: Install deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      # 3. Add the Pi to known_hosts
      - name: Add Pi to known_hosts
        run: |
          ssh-keyscan -p 2222 ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # 4. (Optional) Verify the key and agent
      - name: Debug SSH setup
        run: |
          ls -l ~/.ssh
          ssh -i ~/.ssh/id_ed25519 -p 2222 "${{ secrets.PI_USER }}@${{ secrets.PI_HOST }}" \
            "echo 'SSH key works!'"

      # 5. SSH in and deploy
      - name: Pull & deploy on Pi
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=yes \
              -p 2222 \
              "${{ secrets.PI_USER }}@${{ secrets.PI_HOST }}" \
              "cd /var/www/nickesselman.nl/html && git pull origin main"
